#!/bin/bash
#
# Variable
script="mcapcollector.py"
script_path="${HOME}/mcapcollector"

# Pull the first pid of the any scripts already runninng
pid=`ps -A -o pid,cmd | grep ${script} | grep -v grep | head -n 1 | awk '{print $1}'`

# Verify the process is not running
if [ ${#pid} -eq 0 ]
  then
    echo "Process is not running ...."
    exit
fi

echo "Stopping process"
/bin/kill ${pid}
